@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.tvoyhod.hoofit.ui.CommentFragment",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_939296559 { 
   	label=tvoyhod
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1403126406 { 
   	label=hoofit
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Comment200341979[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Comment</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   date: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   message: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   stars: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   user: User [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommentAdapter976963852[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommentAdapter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   comments: List&lt;Comment&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   context: Context [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listener: OnCommentClickListener [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onBindViewHolder(holder: ViewHolder, position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateViewHolder(parent: ViewGroup, viewType: int): ViewHolder</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeItem(position: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommentFragment1537636401[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommentFragment</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   adapter: CommentAdapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   commentsRef: DatabaseReference [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   reserve: Reserve [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   trail: Trail [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateView(inflater: LayoutInflater, container: ViewGroup, savedInstanceState: Bundle): View</TD></TR>
<TR><TD ALIGN="LEFT" >+ onDeleteComment(position: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Coordinate200341979[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Coordinate</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   latitude: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   longitude: double [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MainActivity2109978989[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainActivity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   binding: ActivityMainBinding [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   transaction: FragmentTransaction [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- createLocationRequest(): LocationRequest</TD></TR>
<TR><TD ALIGN="LEFT" >+ makeTransaction(transaction: FragmentTransaction, fragment: Fragment)</TD></TR>
<TR><TD ALIGN="LEFT" ># onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onFragmentChanged(itemId: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- replaceFragment(fragment: Fragment)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Reserve200341979[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Reserve</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   trails: List&lt;Trail&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ describeContents(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ writeToParcel(parcel: Parcel, i: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Trail200341979[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Trail</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   comments: List&lt;Comment&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commentsCounter: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   coordinatesList: List&lt;Coordinate&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   difficulty: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   length: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stars: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timeRequired: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

User200341979[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)User</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isAdmin: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   likedTrails: List&lt;Trail&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   username: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Utils1899378282[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Utils</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- createImageFile(activity: Activity): File</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteImageFromPreferences(context: Context, key: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getImageFromPreferences(context: Context, key: String): Bitmap</TD></TR>
<TR><TD ALIGN="LEFT" >+ loadImage(context: Context, imageId: String, imageView: ImageView, imageRef: StorageReference)</TD></TR>
<TR><TD ALIGN="LEFT" >+ openFileChooser(activity: Activity): File</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveImageToPreferences(context: Context, key: String, bitmap: Bitmap)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Comment200341979 -> User200341979[label="user
[0..1]"];
CommentAdapter976963852 -> Comment200341979[label="comments
[0..*]"];
CommentAdapter976963852 -> CommentFragment1537636401[label="listener
[0..1]", arrowhead=none];
CommentAdapter976963852 -> Utils1899378282[label="onBindViewHolder() -> loadImage()"];
CommentFragment1537636401 -> CommentAdapter976963852[label="adapter
[0..1]"];
CommentFragment1537636401 -> MainActivity2109978989[label="onCreateView() -> makeTransaction()"];
CommentFragment1537636401 -> Reserve200341979[label="reserve
[0..1]"];
CommentFragment1537636401 -> Trail200341979[label="trail
[0..1]"];
Reserve200341979 -> Trail200341979[label="trails
[0..*]"];
Trail200341979 -> Comment200341979[label="comments
[0..*]"];
Trail200341979 -> Coordinate200341979[label="coordinatesList
[0..*]"];
User200341979 -> Trail200341979[label="likedTrails
[0..*]"];
    
}
@enduml